spring.application.name=scan-and-go-api

# Server settings
server.port=${PORT:8080}

# Database Configurations
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/scan_and_go_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1111}

# JPA Configurations
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: CORS configuration for production
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}